source "https://rubygems.org"

gem "rails", "8.0.2"
gem "sqlite3", "2.6.0"
gem "puma", "6.6.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", "1.18.4", require: false
gem "thruster", "0.1.12", require: false
